# Generated by Django 5.1.4 on 2024-12-14 16:26

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
                ("address", models.CharField(blank=True, max_length=100, null=True)),
                ("phone", models.CharField(blank=True, max_length=10, null=True)),
                ("person", models.CharField(blank=True, max_length=100, null=True)),
                ("type", models.CharField(blank=True, max_length=100, null=True)),
                ("op_bal_cash", models.CharField(blank=True, max_length=20, null=True)),
                ("op_cash_dc", models.CharField(blank=True, max_length=100, null=True)),
                ("op_bal_rtgs", models.CharField(blank=True, max_length=10, null=True)),
                ("op_rtgs_dc", models.CharField(blank=True, max_length=100, null=True)),
                ("round_cash", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "round_cash_dc",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("round_rtgs", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "round_rtgs_dc",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "round_quantity",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("r_date", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "transport_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("marka", models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("type", models.CharField(blank=True, max_length=100, null=True)),
                ("anx_no", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Homepage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "opening_stock",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("pieces", models.CharField(blank=True, max_length=100, null=True)),
                ("rate", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "diff_rate_sale",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("purchase", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Cashentry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "cl_balance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("rec_pay", models.CharField(blank=True, max_length=2, null=True)),
                ("remarks", models.CharField(blank=True, max_length=100, null=True)),
                ("round_date", models.DateField(blank=True, null=True)),
                ("kasar", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "round_cash",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("cash_dc", models.CharField(blank=True, max_length=2, null=True)),
                (
                    "round_rtgs",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("rtgs_dc", models.CharField(blank=True, max_length=2, null=True)),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.account"
                    ),
                ),
            ],
            options={"verbose_name_plural": "Cash Entries",},
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("contact_no", models.CharField(blank=True, max_length=20)),
                ("organization_name", models.CharField(blank=True, max_length=100)),
                ("address", models.TextField(blank=True)),
                ("full_name", models.CharField(default="", max_length=150)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="custom_user_groups",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="custom_user_permissions",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[("objects", django.contrib.auth.models.UserManager()),],
        ),
        migrations.AddField(
            model_name="account",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="myapp.group",
            ),
        ),
        migrations.CreateModel(
            name="JobIssUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_packing", models.DateField(blank=True, null=True)),
                ("esti_no", models.CharField(blank=True, max_length=100, null=True)),
                ("cr_days", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "book",
                    models.ForeignKey(
                        limit_choices_to={"type": "Sale"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookjobiss",
                        to="myapp.account",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partyjobiss",
                        to="myapp.account",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Job Issue",},
        ),
        migrations.CreateModel(
            name="JobIssDown",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marka", models.CharField(blank=True, max_length=100, null=True)),
                ("transport", models.CharField(blank=True, max_length=20, null=True)),
                ("ref_no", models.CharField(blank=True, max_length=20, null=True)),
                ("lr_no", models.CharField(blank=True, max_length=100, null=True)),
                ("bill_no", models.CharField(blank=True, max_length=20, null=True)),
                ("packing", models.CharField(blank=True, max_length=20, null=True)),
                ("gst", models.CharField(blank=True, max_length=100, null=True)),
                ("tcs", models.CharField(blank=True, max_length=20, null=True)),
                ("tds", models.CharField(blank=True, max_length=20, null=True)),
                ("other", models.CharField(blank=True, max_length=100, null=True)),
                ("net_rtgs", models.CharField(blank=True, max_length=20, null=True)),
                ("net_diff", models.CharField(blank=True, max_length=20, null=True)),
                ("total", models.CharField(max_length=20, null=True)),
                (
                    "jobiss_up",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobissdown",
                        to="myapp.jobissup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobRecUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_packing", models.DateField(blank=True, null=True)),
                ("esti_no", models.CharField(blank=True, max_length=100, null=True)),
                ("cr_days", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "book",
                    models.ForeignKey(
                        limit_choices_to={"type": "Purchase"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookjobrec",
                        to="myapp.account",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partyjobrec",
                        to="myapp.account",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Job Receipt",},
        ),
        migrations.CreateModel(
            name="JobRecDown",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marka", models.CharField(blank=True, max_length=100, null=True)),
                ("transport", models.CharField(blank=True, max_length=20, null=True)),
                ("ref_no", models.CharField(blank=True, max_length=20, null=True)),
                ("lr_no", models.CharField(blank=True, max_length=100, null=True)),
                ("bill_no", models.CharField(blank=True, max_length=20, null=True)),
                ("packing", models.CharField(blank=True, max_length=20, null=True)),
                ("gst", models.CharField(blank=True, max_length=100, null=True)),
                ("tcs", models.CharField(blank=True, max_length=20, null=True)),
                ("tds", models.CharField(blank=True, max_length=20, null=True)),
                ("other", models.CharField(blank=True, max_length=100, null=True)),
                ("net_rtgs", models.CharField(blank=True, max_length=20, null=True)),
                ("net_diff", models.CharField(blank=True, max_length=20, null=True)),
                ("total", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "purchaseup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.jobrecup"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JVentry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("c_b", models.CharField(blank=True, max_length=100, null=True)),
                ("amount", models.CharField(blank=True, max_length=100, null=True)),
                ("remark", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "cr_name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Cr_name",
                        to="myapp.account",
                    ),
                ),
                (
                    "dr_name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Dr_name",
                        to="myapp.account",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Production",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("doc_no", models.CharField(blank=True, max_length=100, null=True)),
                ("quantity", models.CharField(blank=True, max_length=100, null=True)),
                ("pieces", models.CharField(blank=True, max_length=20, null=True)),
                ("rec_iss", models.CharField(blank=True, max_length=100, null=True)),
                ("remark", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "issue_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Issue_to",
                        to="myapp.account",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Item",
                        to="myapp.item",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_packing", models.DateField(blank=True, null=True)),
                ("esti_no", models.CharField(blank=True, max_length=100, null=True)),
                ("cr_days", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "book",
                    models.ForeignKey(
                        limit_choices_to={"type": "Purchase"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book1",
                        to="myapp.account",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="party1",
                        to="myapp.account",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Purchase",},
        ),
        migrations.CreateModel(
            name="PurchaseDown",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marka", models.CharField(blank=True, max_length=100, null=True)),
                ("transport", models.CharField(blank=True, max_length=20, null=True)),
                ("ref_no", models.CharField(blank=True, max_length=20, null=True)),
                ("lr_no", models.CharField(blank=True, max_length=100, null=True)),
                ("bill_no", models.CharField(blank=True, max_length=20, null=True)),
                ("packing", models.CharField(blank=True, max_length=20, null=True)),
                ("gst", models.CharField(blank=True, max_length=100, null=True)),
                ("tcs", models.CharField(blank=True, max_length=20, null=True)),
                ("tds", models.CharField(blank=True, max_length=20, null=True)),
                ("other", models.CharField(blank=True, max_length=100, null=True)),
                ("net_rtgs", models.CharField(blank=True, max_length=20, null=True)),
                ("net_diff", models.CharField(blank=True, max_length=20, null=True)),
                ("total", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "purchaseup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.purchaseup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SalesUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_packing", models.DateField(blank=True, null=True)),
                ("esti_no", models.CharField(blank=True, max_length=100, null=True)),
                ("cr_days", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "book",
                    models.ForeignKey(
                        limit_choices_to={"type": "Sale"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales_up_book",
                        to="myapp.account",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales_up_party",
                        to="myapp.account",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Sales",},
        ),
        migrations.CreateModel(
            name="SalesDown",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marka", models.CharField(blank=True, max_length=100, null=True)),
                ("transport", models.CharField(blank=True, max_length=20, null=True)),
                ("ref_no", models.CharField(blank=True, max_length=20, null=True)),
                ("lr_no", models.CharField(blank=True, max_length=100, null=True)),
                ("bill_no", models.CharField(blank=True, max_length=20, null=True)),
                ("packing", models.CharField(blank=True, max_length=20, null=True)),
                ("gst", models.CharField(blank=True, max_length=100, null=True)),
                ("tcs", models.CharField(blank=True, max_length=20, null=True)),
                ("tds", models.CharField(blank=True, max_length=20, null=True)),
                ("other", models.CharField(blank=True, max_length=100, null=True)),
                ("net_rtgs", models.CharField(blank=True, max_length=20, null=True)),
                ("net_diff", models.CharField(blank=True, max_length=20, null=True)),
                ("total", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "salesup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales_downs",
                        to="myapp.salesup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SaudaPur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "suda_no",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("quantity", models.CharField(blank=True, max_length=2, null=True)),
                ("rate", models.CharField(blank=True, max_length=100, null=True)),
                ("amount", models.CharField(blank=True, max_length=100, null=True)),
                ("bnd_kg", models.CharField(blank=True, max_length=100, null=True)),
                ("remarks", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.item"
                    ),
                ),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.account"
                    ),
                ),
            ],
            options={"verbose_name_plural": "Sauda Purchase",},
        ),
        migrations.CreateModel(
            name="SaudaSales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "suda_no",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("quantity", models.CharField(blank=True, max_length=2, null=True)),
                ("rate", models.CharField(blank=True, max_length=100, null=True)),
                ("amount", models.CharField(blank=True, max_length=100, null=True)),
                ("bnd_kg", models.CharField(blank=True, max_length=100, null=True)),
                ("remarks", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.item"
                    ),
                ),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.account"
                    ),
                ),
            ],
            options={"verbose_name_plural": "Sauda Sales",},
        ),
        migrations.CreateModel(
            name="SelectCash",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.account"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sr", models.CharField(blank=True, max_length=200, null=True)),
                ("item_name", models.CharField(blank=True, max_length=20, null=True)),
                ("sizes", models.CharField(blank=True, max_length=200, null=True)),
                ("pcs", models.CharField(blank=True, max_length=20, null=True)),
                ("quantity", models.CharField(blank=True, max_length=200, null=True)),
                ("b_rate", models.CharField(blank=True, max_length=20, null=True)),
                ("rate", models.CharField(blank=True, max_length=200, null=True)),
                ("amount", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "table_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tables",
                        to="myapp.salesup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TableJobIss",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sr", models.CharField(blank=True, max_length=200, null=True)),
                ("item_name", models.CharField(blank=True, max_length=20, null=True)),
                ("sizes", models.CharField(blank=True, max_length=200, null=True)),
                ("pcs", models.CharField(blank=True, max_length=20, null=True)),
                ("quantity", models.CharField(blank=True, max_length=200, null=True)),
                ("b_rate", models.CharField(blank=True, max_length=20, null=True)),
                ("rate", models.CharField(blank=True, max_length=200, null=True)),
                ("amount", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "table_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobiss_table",
                        to="myapp.jobissup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TableJobRec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sr", models.CharField(blank=True, max_length=200, null=True)),
                ("item_name", models.CharField(blank=True, max_length=20, null=True)),
                ("sizes", models.CharField(blank=True, max_length=200, null=True)),
                ("pcs", models.CharField(blank=True, max_length=20, null=True)),
                ("quantity", models.CharField(blank=True, max_length=200, null=True)),
                ("b_rate", models.CharField(blank=True, max_length=20, null=True)),
                ("rate", models.CharField(blank=True, max_length=200, null=True)),
                ("amount", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "table_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobrec_table",
                        to="myapp.jobrecup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tablenew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sr", models.CharField(blank=True, max_length=200, null=True)),
                ("item_name", models.CharField(blank=True, max_length=20, null=True)),
                ("sizes", models.CharField(blank=True, max_length=200, null=True)),
                ("pcs", models.CharField(blank=True, max_length=20, null=True)),
                ("quantity", models.CharField(blank=True, max_length=200, null=True)),
                ("b_rate", models.CharField(blank=True, max_length=20, null=True)),
                ("rate", models.CharField(blank=True, max_length=200, null=True)),
                ("amount", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "table_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_table",
                        to="myapp.purchaseup",
                    ),
                ),
            ],
        ),
    ]
